"use client";

/**
 * error.tsx — Global error boundary (Next.js App Router convention)
 *
 * Next.js requires this to be a Client Component. It automatically wraps
 * every route segment that doesn't have its own error.tsx, so any unhandled
 * render error or Server Component exception will land here instead of
 * producing a blank screen.
 *
 * IMPORTANT: Never expose `error.message` or `error.stack` to the UI in
 * production — they can leak internal implementation details. The digest
 * (a short opaque hash generated by Next.js) is safe to show because it
 * contains no sensitive information and helps with support triage.
 */

import { useEffect } from "react";

interface ErrorPageProps {
  error: Error & { digest?: string };
  reset: () => void;
}

export default function GlobalError({ error, reset }: ErrorPageProps) {
  // Log to whatever observability sink is wired up (Sentry, Datadog, etc.)
  // console.error is used here as a safe default; replace with your logger.
  useEffect(() => {
    console.error("[error-boundary]", error.digest ?? error.message);
  }, [error]);

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Nav — minimal, no data dependencies that could themselves error */}
      <header className="sticky top-0 z-10 border-b border-gray-100 bg-white/80 backdrop-blur-md">
        <div className="mx-auto flex max-w-7xl items-center px-4 py-3 sm:px-6 lg:px-8">
          <a
            href="/"
            className="flex items-center gap-2 rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-500"
          >
            <span aria-hidden="true" className="text-2xl">🌀</span>
            <span className="text-xl font-extrabold tracking-tight text-violet-700">
              AirFlex
            </span>
          </a>
        </div>
      </header>

      {/* Error content */}
      <main className="flex flex-1 items-center justify-center px-4 py-16 sm:px-6">
        <div className="w-full max-w-md text-center">
          {/* Illustration */}
          <span aria-hidden="true" className="text-6xl">⚡</span>

          <h1 className="mt-6 text-2xl font-extrabold tracking-tight text-gray-900">
            Something went wrong
          </h1>

          <p className="mt-3 text-sm text-gray-500 leading-relaxed">
            An unexpected error occurred while loading this page. Our team has
            been notified. You can try again or head back to the marketplace.
          </p>

          {/* Digest — safe to surface, helps with support without leaking internals */}
          {error.digest && (
            <p className="mt-3 font-mono text-xs text-gray-400">
              Error ID: {error.digest}
            </p>
          )}

          {/* Actions */}
          <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
            <button
              type="button"
              onClick={reset}
              className="inline-flex items-center justify-center rounded-xl bg-violet-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-violet-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-offset-2"
            >
              Try again
            </button>

            <a
              href="/"
              className="inline-flex items-center justify-center rounded-xl border border-gray-200 bg-white px-6 py-3 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-offset-2"
            >
              Back to marketplace
            </a>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 bg-white">
        <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
          <p className="text-center text-xs text-gray-400">
            &copy; {new Date().getFullYear()} AirFlex — Open source under the MIT License.
          </p>
        </div>
      </footer>
    </div>
  );
}
